name: Test and Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: contracts/package-lock.json

    - name: Install dependencies
      run: |
        cd contracts
        npm ci

    - name: Run tests
      run: |
        cd contracts
        npm test

    - name: Run coverage
      run: |
        cd contracts
        npx hardhat coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./contracts/coverage.json
        flags: contracts
        name: solidity-coverage
        fail_ci_if_error: false

    - name: Generate coverage badge
      run: |
        cd contracts
        npm install -g coverage-badges-cli
        coverage-badges --input coverage.json --output coverage-badge.svg 